# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
cache:
  paths:
    - node_modules
pages:
  stage: deploy
  image: node:8-alpine
  before_script:
    - npm i
    - npm run prepare
  script:
    - mv ./prepared ./public
  artifacts:
    paths:
    - public
  only:
  - master
